### ISSUE TITLE
Errors when example script is passed to locasploit stdin

### ISSUE THREAD

**Issue by pm-cz** [lightfaith/locasploit#1]
If a script is passed to locasploit stdin and said script creates background jobs and finishes before them, errors may occur.
For example: `./locasploit.py < cveupdate` generates many errors 
`[-] Cannot operate on a closed database.`

**Comment by lightfaith** [comment]
Race condition in source/libs/scheduler.py allowed job creation just before main scheduler thread termination, generating database access error messages. Fixed in https://github.com/lightfaith/locasploit/commit/31d28cd4ba1f99d211ee8383227254147f9242a5.

Note that providing input as `cat cveupdate | ./locasploit.py` or `./locasploit.py < cveupdate` is currently not supported, as EOF (Ctrl+D) is used for program termination. The correct use is `./locasploit.py -c cveupdate`.
